# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-10 11:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180910_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
