# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-12 17:52
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20180912_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='photos',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
