# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-12 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20180912_1752'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='address',
            new_name='address_line1',
        ),
        migrations.AddField(
            model_name='school',
            name='address_line2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='area',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='city',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='state',
            field=models.TextField(blank=True, null=True),
        ),
    ]
