# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-13 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20180913_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='facilities',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='facility_preferred',
            field=models.ManyToManyField(to='main.School'),
        ),
        migrations.DeleteModel(
            name='Facilities',
        ),
    ]
